# -*- coding: utf-8 -*-

Config = {
    'categories': { 
        'documentary',
        'entertainment',
        'information',
        'kids',
        'movie',
        'series',
        'sport',
    },

    'genres': [
        'action',               'actuality',            'adventure',        'adventuresport',
        'aerialsport',          'americanfootball',     'animallife',       'animalworld',
        'animation',            'aquaticsport',         'art',              'athletic',
        'baby',                 'baseball',             'basketball',       'beachfootball',
        'biathlon',             'billiard',             'biography',        'boardgame',
        'bullfighting',         'business',             'ceremony',         'civilization',
        'classic',              'classicalmusic',       'comedy',           'contest',
        'cricket',              'crime',                'crimestory',       'culturalmagazine',
        'culture',              'curling',              'cycling',          'dance',
        'darts',                'debate',               'decoration',       'didactic',
        'drama',                'ecology',              'economy',          'education',
        'environment',          'equestrian',           'esoteric',         'event',
        'extremesport',         'fame',                 'family',           'fantasy',
        'fashion',              'fiction',              'fightingsport',    'fishing',
        'football',             'futsal',               'gala',             'gastronomy',
        'golf',                 'gymnastic',            'handball',         'health',
        'historicalseries',     'history',              'hockey',           'horror',
        'horsebackriding',      'hunting',              'icehockey',        'internationalnews',
        'interview',            'kidsseries',           'lifestyle',        'magazine',
        'manualarts',           'martialarts',          'motorcycling',     'motorsport',
        'music',                'musical',              'mystery',          'nature',
        'news',                 'newsmagazine',         'olympicgames',     'opera',
        'opinion',              'padel',                'paranormal',       'pets',
        'politics',             'realimageseries',      'realityshow',      'regionalnews',
        'religion',             'report',               'rollerhockey',     'romance',
        'rugby',                'science',              'scifi',            'skating',
        'ski',                  'snooker',              'soapopera',        'social',
        'society',              'sportnews',            'sportsmagazine',   'strengthsports',
        'supernatural',         'surf',                 'survival',         'swimming',
        'tabletennis',          'talentshow',           'talkshow',         'technologymagazine',
        'technology',           'tennis',               'thriller',         'travel',
        'triathlon',            'unusual',              'videogames',       'voleyball',
        'war',                  'weather',              'wellbeing',        'western',
        'wintersports',
        'other',
    ],

    'actors': [
        'Guy Fieri',                    'Rodger Bumpass',
        'Clancy Brown',                 'Tom Kenny',
        'Bill Fagerbakke',              'Andromeda Dunker',
        'Jeff Tremaine',                'Shane Nickerson',
        'Rob Dyrdek',                   'LL Cool J',
        'Kourtney Kardashian',          'Khloé Kardashian',
        'Kim Kardashian West',          'Suzanne Whang',
        'Wolfgang Hess',                'Seth MacFarlane',
        'Hank Azaria',                  'Julie Kavner',
        'Nancy Cartwright',             'Dan Castellaneta',
        'Yeardley Smith',               'Harry Shearer',
        'Filipa Gomes',                 'Jorja Fox',
        'Eric Szmanda',                 'George Eads',
        'Chris Broyles',                'Rudolph van Veen',
        'Ted Danson',                   'Elisabeth Shue',
        'Alyson Hannigan',              'Kris Jenner',
        'Rick Harrison',                'Salvador Nery',
        'Brandi Passante',              'Jarrod Schulz',
        'Kannon Gowen',                 'Laura Dotson',
        'Pêpê Rapazote',                'Taraji P. Henson',
        'Alex Borstein',                'Timothy Olyphant',
        'Mila Kunis',                   'Austin \'Chumlee\' Russell', 
        'Michael Ernst',                'Corey Harrison',
        'Dan Dotson',                   'Kadeem Hardison',
        'Richard Harrison',             'Seth Green',
        'Zendaya',                      'Veronica Dunne',
        'Tammy Townsend',               'Damien Laquet',
        'Ron Perlman',                  'Sofía Vergara',
        'Jesse Tyler Ferguson',         'Eric Stonestreet',
        'Ed O\'Neill',                  'Julie Bowen',
        'Ty Burrell',                   'Richard Hammond',
        'Elissa Lansdell',              'Shawn Hewson',
        'Joe Zee',                      'Khyber Zaffarkhan',
        'Boyd Flinders',                'Jorge Corrula',
        'Alisdair Simpson',             'Jenny Steele',
        'Glen Heggstad',                'Kevin Chapman',
        'Salina Mather',                'Sophie Morton',
        'Dominic Colenso',              'Jack Merivale',
        'James Caviezel',               'Matthew Ryan Anderson',
        'Bonnie Kilcher',               'Sébastien Desjours',
        'Charlotte Kilcher',            'Bray Poor',
        'Annouck Hautbois',             'Laetitia Lefebvre',
        'Atz Kilcher',                  'Damien Ferrette',
        'Bárbara Lourenço',             'Chris O\'Donnell',
        'Brad Dourif',                  'Yves Barsacq',
        'Linda Hunt',                   'Michael Emerson',
        'Matthew Gray Gubler',          'Kirsten Vangsness',
        'Ian McShane',                  'Christine Bellier',
        'Caroline Combes',              'Pauline Brunner',
        'Thomas Gibson',                'Sally Martin',
    ],

    'directors': [
        'Marv Wolfman',                     'Arnold Drake',
        'George Pérez',                     'Nick Jennings',
        'J.G. Quintel',                     'Katie Krentz',
        'Benjamin Bocquelet',               'Pendleton Ward',
        'Scott Fellows',                    'Tim Hill',
        'Stephen Hillenburg',               'Chris  Nee',
        'Derek Drymon',                     'Jed Elinoff',
        'Scott Thomas',                     'Matt Groening',
        'Daniel Duda',                      'Sascha Paladino',
        'Anthony E. Zuiker',                'Fréderic Mège',
        'Lauren Faust',                     'François Narboux',
        'Steven Bortko',                    'Peter Browngardt',
        'Nicky Phelan',                     'Skyler Page',
        'Cyril Adam',                       'Niamh  Sharkey',
        'David Michel',                     'Chris Ray',
        'Craig Gerber',                     'Rebecca Sugar',
        'Hiroshi "Fujiko" Fujimoto',        'Frédéric Azémar',
        'António Pinhão Botelho',           'Emmanuelle Fleury',
        'Fabien Limousin',                  'Motoo Abiko',
        'Seth MacFarlane',                  'Chris Labonte',
        'Paul H. Brown',                    'Eric Cazes',
        'Matthew Bennett',                  'Andrés Lieban',
        'Corinne Marshall',                 'Jonathan Nolan',
        'Christopher Lloyd',                'Steven Levitan',
        'Dan Schneider',                    'Thom Beers',
        'Jeff Davis',                       'Bob Boyle',
        'Lionel Kerjean',                   'Jorge Cardoso',
        'Andrew W. Marlowe',                'David Milch',
        'Mark Cendrowski',                  'Jennifer Pertsch',
        'Tom McGillis',                     'Shane Brennan',
        'Alexs Stadermann',                 'Leonard Freeman',
        'Daniel Chong',                     'Oleg Kuzovkov',
        'Michael Sellers',                  'Duarte Teixeira',
        'Michael Pearlman',                 'Jed Spingam',
        'Tim Kring',                        'Claude Allix',
        'Luther McLaurin',                  'Lane Lueras',
        'Heath Kenny',                      'Myles McLeod',
        'Junichi Masuda',                   'Satoshi Tajiri',
        'Ken Sugimori',                     'Meredith Stiehm',
        'Jamie LeClaire',                   'Jorge Aguirre',
        'Merle-Anne Ridley',                'Eric Darnell',
        'Christian De Vita',                'Tom McGrath',
        'Richard Gitelson',                 'Phil Lafrance',
        'Chuck Lorre',                      'Michael Patrick King',
        'Ram Ganapati Rao',                 'Matt Fleckenstein',
        'I. Marlene King',                  'Michael Feldman',
        'Whitney Cummings',                 'Olivier Derynck',
        'Gary Doodles',                     'Chris Peterson',
        'Craig Thomas',                     'Mike Barker',
        'Bryan Moore',                      'Roberts Gannaway',
    ]

}
